import React from 'react';
import { useFarmData } from '../context/FarmContext';
import { BrainCircuit, CheckCircle2 } from 'lucide-react';

export default function AIInsights() {
  const { zones } = useFarmData();

  const getPriorityStyle = (priority) => {
    switch (priority) {
      case 'CRITICAL': return 'bg-red-50 border-red-200 text-red-900';
      case 'HIGH': return 'bg-orange-50 border-orange-200 text-orange-900';
      case 'MEDIUM': return 'bg-yellow-50 border-yellow-200 text-yellow-900';
      default: return 'bg-green-50 border-green-200 text-green-900';
    }
  };

  const getPriorityBadge = (priority) => {
    switch (priority) {
      case 'CRITICAL': return 'bg-red-200 text-red-800';
      case 'HIGH': return 'bg-orange-200 text-orange-800';
      case 'MEDIUM': return 'bg-yellow-200 text-yellow-800';
      default: return 'bg-green-200 text-green-800';
    }
  };

  const actionsRequired = zones.filter(z => z.analysis.riskLevel !== 'LOW');

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center gap-3">
        <BrainCircuit className="w-8 h-8 text-purple-600" />
        <div>
          <h1 className="text-2xl font-bold text-gray-900">AI Recommendations</h1>
          <p className="text-gray-500">Actionable insights generated by the Farm Decision Engine.</p>
        </div>
      </div>

      <div className="space-y-6">
        {actionsRequired.length === 0 ? (
           <div className="bg-white border border-gray-200 rounded-xl p-12 text-center flex flex-col items-center">
             <CheckCircle2 className="w-16 h-16 text-green-500 mb-4" />
             <h3 className="text-xl font-bold text-gray-900">Farm conditions are optimal</h3>
             <p className="text-gray-500 mt-2 max-w-md">
               The AI engine has analyzed all zones and detected no significant stress or required actions at this time.
             </p>
           </div>
        ) : (
          actionsRequired.map(zone => (
            <div key={zone.zoneId} className={`border rounded-xl p-6 shadow-sm ${getPriorityStyle(zone.analysis.riskLevel)}`}>
              <div className="flex justify-between items-start mb-4">
                <div>
                  <div className="flex items-center gap-3 mb-1">
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${getPriorityBadge(zone.analysis.riskLevel)}`}>
                      Priority: {zone.analysis.riskLevel}
                    </span>
                    <span className="font-semibold">{zone.name} - {zone.cropType}</span>
                  </div>
                  <h3 className="text-xl font-bold mt-3">"{zone.analysis.recommendedAction === 'IRRIGATE' ? 'Consider irrigation soon.' : 'Monitor plant condition.'}"</h3>
                </div>
              </div>
              
              <div className="bg-white/60 backdrop-blur rounded-lg p-4 mb-4">
                <h4 className="text-sm font-bold text-gray-700 uppercase tracking-wider mb-2">AI Analysis Reason:</h4>
                <p className="text-gray-800">{zone.analysis.explanation}</p>
              </div>

              <div className="flex gap-6 border-t border-black/10 pt-4 mt-2">
                <div>
                  <span className="text-xs text-gray-600 block mb-1">Soil Moisture</span>
                  <span className="font-bold">{zone.sensorData.soilMoisture.toFixed(1)}%</span>
                </div>
                <div>
                  <span className="text-xs text-gray-600 block mb-1">Temperature</span>
                  <span className="font-bold">{zone.sensorData.airTemperature.toFixed(1)}°C</span>
                </div>
                <div>
                  <span className="text-xs text-gray-600 block mb-1">Rainfall</span>
                  <span className="font-bold">{zone.sensorData.rainfall} mm</span>
                </div>
                <div>
                  <span className="text-xs text-gray-600 block mb-1">Health Score</span>
                  <span className="font-bold">{zone.analysis.overallHealthScore}%</span>
                </div>
              </div>
            </div>
          ))
        )}

        {/* Display Low Priority items always */}
        {zones.filter(z => z.analysis.riskLevel === 'LOW').map(zone => (
          <div key={zone.zoneId} className="border border-gray-200 bg-white rounded-xl p-6 shadow-sm opacity-70">
             <div className="flex items-center gap-3 mb-3">
               <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-gray-100 text-gray-600">
                 Priority: LOW
               </span>
               <span className="font-semibold text-gray-700">{zone.name}</span>
             </div>
             <h3 className="text-lg font-bold text-gray-800">"No immediate action required."</h3>
             <p className="text-sm text-gray-600 mt-2">Conditions are within preferred thresholds for {zone.cropType}.</p>
          </div>
        ))}
      </div>
    </div>
  );
}
